### ISSUE TITLE
4.1 running but lots of empty lines in log

### ISSUE THREAD

**Issue by GravityRZ** [marcoraddatz/homebridge-docker#39]
DSM version 6.1.4.15217 update 3
docker version 17.05.0-0349
homebridge v4.1

i managed to install the latest 4.1 homebridge version but there seems to  be a lot of empty lines in the log files. Also i see some code i did not see before.

at first 4.1 was running but nothing was detected. this was caused by the bonjour service running
here are my findings
4.0 bug with duplicate UUID error is there
4.1 bug with duplicate UUID error is STILL there

4.0 running fine, even with bonjour service active
4.1 running fine but only after disabling bonjour service(before that nothing was detected

4.0 local time was not working
4.1 confirmation that local time is working, EVEN WITHOUT .env file present(how can this be)

4.0 log file looking normal. every line has a time stamp and an entry
scrolling up and down looks normal

4.1 logfile not normal. lot's of empty lines with only timestamps. 1 mean really a lot of empty lines.(total 500+ lines) screenshot only shows part of it with some weird code about payload.
scrolling inside log looks weird. lines with no timestamp and no std out appear.
it looks like the screen has problems with some strange code
scrolling down goes ok but scrolling vack up makes lines disappear

![image](https://user-images.githubusercontent.com/16853535/34117232-58dde53c-e41b-11e7-9059-d693a1b7f6b3.png)

**Comment by marcoraddatz** [comment]
Many thanks for the feedback! 

1. The UUID bug only got fixed in 4.2 (develop branch). I tried it out and got no problems running, but cannot guarantee, that it fixes the issues (#7).

2. What does the local time message say? In v4.1 it should be sth. like "Sun Dec 17 15:58:06 CET 2017". v4.2 also prints out an additional message: "Updated timezone to 'Europe/Berlin'." (Btw. you might also set the timezone via DSM as TZ env).

3. I also saw the empty lines, but don't know where they come from. The ones right before the "Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:" could be a QR code, which gets displayed via terminmal, but unfortunately not via DSM. But I also noticed many white lines before – they went away when I scrolled them in DSM. So it might be a bug due to DSM.

**Comment by GravityRZ** [comment]
i was just checking the time in the log
it says 2017-12-18 17:56:01 (where the time stamp of the entry is 16:56:01)

before 4.1 the timestamp of the entry and the log was both the same (one hour behind)

**Comment by Sweetgenius19** [comment]
I have the empty lines issue also. If i scroll up the data is there.
Is there a way to have the Docker Time match the Image time now that I have set the Timezone in the .env file? I tried adding a TZ environment variable in the container but did not change the docker time stamps.

**Comment by marcoraddatz** [comment]
Sadly, I don't think so. The timestamps seem to come from DSM and I don't know how to sync them.

**Comment by GravityRZ** [comment]
tested the latest development branch(no way to tell if this is 4.2)
UUID bug is still there

also still empty log lines but the scrolling seems to work again

restarted 4.1 again and the log scrolling improved also(still empty lines but a lot less)
The only thing i changed was not forcing version 4.0.33 (commented out HOMEBRIDGE_VERSION.

there is also a new docker version 0367 available on synology

**Comment by marcoraddatz** [comment]
Thanks! Closing this one.
